name = "meals-for-life"
type = "webpack"
account_id = "" # You'll fill this in later
workers_dev = true
route = ""
zone_id = ""

[site]
bucket = "./public"
entry-point = "workers-site"

[env.production]
workers_dev = false
route = "yourdomain.com/*"
zone_id = "" # You'll fill this in later

[build]
command = "npm run build" 